services:
  frontend:
    image: tellinkengenharia/anc-brasil-web:latest
    container_name: anc-brasil-web
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - anc-network

  backend:
    image: tellinkengenharia/anc-brasil-api:latest
    container_name: anc-brasil-api
    ports:
      - "8089:8089"
    environment:
      - NODE_ENV=production
    depends_on:
      - mysql
    networks:
      - anc-network
    restart: always

  mysql:
    image: mysql:8.0
    container_name: anc-brasil-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_anc_brasil
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - anc-network

volumes:
  db_data:

networks:
  anc-network:
    driver: bridge
